server:
  port: 8083
  servlet:
    context-path: /ddms
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/DDMS?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  main:
    banner-mode: "off"
logging:
  level:
    com.knowater.ddms.dao: debug
    org.springframework.boot.autoconfigure: ERROR

mybatis:
  type-aliases-package: com.xiaoxiao.ad.dao
  mapper-locations: classpath:mapper/*.xml
